# Generated by Django 4.2.18 on 2025-02-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_remove_sale_customer_name_sale_customer'),
        ('payments', '0003_payment_payment_method_payment_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sale',
        ),
        migrations.CreateModel(
            name='Sale_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
    ]
