# Generated by Django 4.2.18 on 2025-02-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_sale_sale_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_payment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='sale_payment',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Sale_Payment',
        ),
    ]
