# Generated by Django 4.2.18 on 2025-02-11 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_amount_delete_serviceamount'),
        ('customers', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_type',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_info', to='services.service'),
            preserve_default=False,
        ),
    ]
