# Generated by Django 4.2.18 on 2025-02-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_servicerecord_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
