# Generated by Django 4.2.18 on 2025-02-08 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_remove_sale_customer_name_sale_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_service_amount_delete_serviceamount'),
        ('commissions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
        ),
        migrations.RemoveField(
            model_name='commissionsetting',
            name='role',
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeCommission',
        ),
    ]
